---
site_name: "LAB-11090 - Getting Started with Webex Calling: Hands-On Lab" # This must begin with the session ID, e.g. LABXXX-1234 This is my Cisco Live Lab
site_description: "LAB-11090 - Getting Started with Webex Calling: Hands-On Lab" # must be same as "site_name"
site_author: Susan Parrish
copyright: Copyright &copy; 2026 Cisco
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.instant
    - navigation.top
    - navigation.footer
    - search.suggest
    - content.code.copy
    - toc.integrate
  custom_dir: docs/overrides
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: template_assets/webexLogo91.png
  favicon: template_assets/webex75.png
extra:
  generator: false
  repo: "https://github.com/WebexCC-SA/LAB-11090.git"
  site_event: test
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - template_assets/js/newLoad.js
  - template_assets/js/setInfo.js
plugins:
  - search
  - macros
  # - with-pdf:
  #     cover_title: LABXXX-1234
  #     cover_subtitle: My famous WebexOne Lab
  #     cover_logo: template_assets/wx1Splash_new.gif
  - glightbox:
      touchNavigation: true
      loop: false
      effect: fade
      slide_effect: slide
      width: 100%
      height: auto
      zoomable: true
      draggable: false
      skip_classes:
      - custom-skip-class-name
      auto_caption: true
      caption_position: top
markdown_extensions:
  - md_in_html
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - tables
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
      
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
nav:
  - Home: index.md
  - About this Lab:
    - Overview and Objectives: lab-overview-objectives.md
    - Customer Scenario: example-customer-scenario.md
    - Getting Started: getting-started-with-your-environment.md
  - Lab Activities:
    - Lab 1 - Organization Settings: lab-1-organization-settings.md
    - Lab 2 - Location Settings: lab-2-location-settings.md
    - Lab 3 - Users: lab-3-users.md
    - Lab 4 - Devices and Workspaces: lab-4-devices-and-workspaces.md
    - Lab 5 - Calling Features: lab-5-configuring-calling-features.md
    - Lab 6 - Creating Queues: lab-6-creating-queues.md
    - Lab 7 - Main Number Auto Attendant: lab-7-create-the-aa-for-the-main-number.md
    - Lab 8 - User and Device Settings: lab-8-user-and-device-settings.md
    - Lab 9 - Test Call Routing and Features: lab-9-test-main-call-routing-and-features.md
  - Resources:
    - Useful Links: useful-links.md
